# Generated by Django 5.1.3 on 2024-11-16 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_organizer_alter_event_partners_profile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='partners',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.organizer'),
        ),
    ]
