# Generated by Django 5.1.3 on 2024-11-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_alter_event_partners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
