# Generated by Django 5.1.3 on 2024-11-16 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='partners',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.PROTECT, to='Events.organizer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Events.category'),
        ),
    ]
