# Generated by Django 5.1.3 on 2024-11-16 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_category_alter_event_partners_alter_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='special',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='Events.special'),
        ),
    ]
