# Generated by Django 5.1.3 on 2024-11-16 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_category_alter_event_partners_alter_event_category'),
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Events.category'),
        ),
    ]
